### ISSUE TITLE
MemoryError on z1d.large ec2

### ISSUE THREAD

**Issue by j-000** [j-000/kc#1]
```
ubuntu@ip-172-31-40-153:~/kc$ python3 kc.py 11111111 100000000
 25%|██████████████████████████████████████▎                                                                                                                 | 22368942/88888889 [13:42<40:46, 27188.00it/s]
Traceback (most recent call last):
  File "kc.py", line 59, in <module>
    main(_min=int(_min), _max=int(_max))
  File "kc.py", line 38, in main
    r = kaprekar_constant(i)
  File "kc.py", line 31, in kaprekar_constant
    return kaprekar_constant(c, loop=loop+1)
  File "kc.py", line 31, in kaprekar_constant
    return kaprekar_constant(c, loop=loop+1)
  File "kc.py", line 31, in kaprekar_constant
    return kaprekar_constant(c, loop=loop+1)
  [Previous line repeated 12 more times]
  File "kc.py", line 21, in kaprekar_constant
    seen_freq[str(p)] = 1
MemoryError
ubuntu@ip-172-31-40-153:~/kc$ 

```

May need to optimise the script to be more memory efficient or get a better instance.

**Comment by j-000** [comment]
Fixed with a r5ad.4xlarge instance. Results coming up.
